# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

font_family      FiraMono Nerd Font Mono
# font_family      UbuntuMono Nerd Font
# font_family      Monaco
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12

#: }}}

#: Performance tuning {{{

sync_to_monitor yes

#: }}}

#: Window layout {{{

remember_window_size  yes

enabled_layouts Splits

window_border_width 0.5pt

window_margin_width 0

window_padding_width 1 3

placement_strategy center

active_border_color #aaaaaa

inactive_border_color #555555

# hide_window_decorations yes

#: }}}

#: Tab bar {{{

tab_bar_edge top

tab_bar_margin_height 0.0 0.0

tab_bar_style powerline

tab_bar_align center

tab_bar_min_tabs 2

tab_fade 0.25 0.5 0.75 1

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index} {title}"

active_tab_foreground   #111
active_tab_background   #666
# active_tab_font_style   bold-italic

inactive_tab_foreground #888
inactive_tab_background #444
# inactive_tab_font_style normal

#: }}}

#: Color scheme {{{

include ./kitty-themes/themes/SpaceGray_Eighties.conf

# background            #000000

# background_opacity 1.0

# background_blur 100

# background_image ~/Pictures/Wallpapers/terminal_evangelion.png

# background_tint 0.98

# background_tint_gaps 0.98

# dim_opacity 0.4

#: }}}

#: Advanced {{{

allow_remote_control yes

listen_on unix:@mykitty

#: }}}

#: OS specific tweaks {{{

# macos_titlebar_color system

macos_option_as_alt yes

# macos_hide_from_tasks no

# macos_quit_when_last_window_closed no

# macos_window_resizable yes

# macos_thicken_font 0

# macos_traditional_fullscreen no

# macos_show_window_title_in all

# macos_menubar_title_max_length 0

# macos_custom_beam_cursor no

# macos_colorspace srgb

#: }}}

#: Keyboard shortcuts {{{

# map alt+q send_text all \u001b
# map opt+h send_text all \u33[D
map ctrl+shift+f11 toggle_fullscreen

map opt+h left
map opt+j down
map opt+k up
map opt+l right

map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l
# map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j "^.* - nvim$"
# map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k "^.* - nvim$"
# map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h "^.* - nvim$"
# map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l "^.* - nvim$"

map ctrl+b>h launch --cwd=current --location=vsplit
map ctrl+b>v launch --cwd=current --location=hsplit
map ctrl+b>x close_window

#: }}}

# use-kitty-keyboard-protocol = true
