return {
    enabled = true,
    jump = {
        jumplist = true, -- save the current position in the jumplist
        tagstack = true, -- save the current position in the tagstack
        reuse_win = true, -- reuse an existing window if the buffer is already open
        close = true, -- close the picker when jumping/editing to a location (defaults to true)
        match = true, -- jump to the first match position. (useful for `lines`)
    },
    win = {
        -- input window
        input = {
            keys = {
                ["<Esc>"] = "cancel",
                -- ["q"] = "close",
                -- ["/"] = "toggle_focus",
                ["<C-Down>"] = { "history_forward", mode = { "i", "n" } },
                ["<C-Up>"] = { "history_back", mode = { "i", "n" } },
                -- ["<C-c>"] = { "cancel", mode = "i" },
                ["<CR>"] = { "confirm", mode = { "n", "i" } },
                ["<C-w>"] = { "<c-s-w>", mode = { "i" }, expr = true, desc = "delete word" },
                ["<Down>"] = { "list_down", mode = { "i", "n" } },
                ["<Up>"] = { "list_up", mode = { "i", "n" } },
                -- ["<S-Tab>"] = { "select_and_prev", mode = { "i", "n" } },
                -- ["<Tab>"] = { "select_and_next", mode = { "i", "n" } },
                ["<a-f>"] = { "toggle_follow", mode = { "i", "n" } },
                ["<a-h>"] = { "toggle_hidden", mode = { "i", "n" } },
                ["<a-i>"] = { "toggle_ignored", mode = { "i", "n" } },
                ["<a-m>"] = { "toggle_maximize", mode = { "i", "n" } },
                ["<a-p>"] = { "toggle_preview", mode = { "i", "n" } },
                ["<c-g>"] = { "toggle_live", mode = { "i", "n" } },
                ["?"] = "toggle_help_input",
                ["<a-d>"] = { "inspect", mode = { "n", "i" } },
                ["<a-w>"] = { "cycle_win", mode = { "i", "n" } },
                ["<c-a>"] = { "select_all", mode = { "n", "i" } },
                -- ["<c-k>"] = { "list_up", mode = { "i", "n" } },
                -- ["<c-j>"] = { "list_down", mode = { "i", "n" } },
                ["<c-u>"] = { "list_scroll_up", mode = { "i", "n" } },
                ["<c-d>"] = { "list_scroll_down", mode = { "i", "n" } },
                ["G"] = "list_bottom",
                ["gg"] = "list_top",
                ["j"] = "list_down",
                ["k"] = "list_up",
                -- ["<c-b>"] = { "preview_scroll_up", mode = { "i", "n" } },
                -- ["<c-f>"] = { "preview_scroll_down", mode = { "i", "n" } },
                -- ["<c-p>"] = { "list_up", mode = { "i", "n" } },
                -- ["<c-n>"] = { "list_down", mode = { "i", "n" } },
                ["<c-q>"] = { "qflist", mode = { "i", "n" } },
                ["<c-t>"] = { "tab", mode = { "n", "i" } },
                -- ["<c-s>"] = { "edit_split", mode = { "i", "n" } },
                -- ["<c-v>"] = { "edit_vsplit", mode = { "i", "n" } },
                ["<c-w>H"] = "layout_left",
                ["<c-w>J"] = "layout_bottom",
                ["<c-w>K"] = "layout_top",
                ["<c-w>L"] = "layout_right",
                -- ["q"] = "close",
                -- Additional
                ["<c-h>"] = { "vsplit", mode = { "n", "i" } },
                ["<c-v>"] = { "split", mode = { "n", "i" } },
                ["<S-Tab>"] = { "list_up", mode = { "n", "i" } },
                ["<Tab>"] = { "list_down", mode = { "n", "i" } },
                ["<c-y>"] = { "select_and_next", mode = { "n", "i" } },
                ["<c-n>"] = { "select_and_prev", mode = { "n", "i" } },
                -- ["<CR>"] = { "tabdrop", mode = { "n", "i" } },
                ["<c-CR>"] = { "confirm", mode = { "n", "i" } },
                ["<c-f>"] = { "toggle_focus", mode = { "n", "i" } },
                ["<C-c>"] = { "close", mode = { "n", "i" } },
            },
            b = {
                minipairs_disable = true,
            },
        },
        -- result list window
        list = {
            keys = {
                ["<Esc>"] = "cancel",
                -- ["q"] = "close",
                ["i"] = "focus_input",
                -- ["/"] = "toggle_focus",
                ["<2-LeftMouse>"] = "confirm",
                ["<CR>"] = "confirm",
                ["<S-CR>"] = { { "pick_win", "jump" } },
                ["<Up>"] = "list_up",
                ["<Down>"] = "list_down",
                -- ["<S-Tab>"] = { "select_and_prev", mode = { "n", "x" } },
                -- ["<Tab>"] = { "select_and_next", mode = { "n", "x" } },
                ["<a-f>"] = "toggle_follow",
                ["<a-h>"] = "toggle_hidden",
                ["<a-i>"] = "toggle_ignored",
                ["<a-m>"] = "toggle_maximize",
                ["<a-p>"] = "toggle_preview",
                ["?"] = "toggle_help_list",
                ["<a-d>"] = "inspect",
                ["<a-w>"] = "cycle_win",
                ["<c-a>"] = "select_all",
                ["<c-u>"] = "list_scroll_up",
                ["<c-d>"] = "list_scroll_down",
                -- ["<c-b>"] = "preview_scroll_up",
                -- ["<c-f>"] = "preview_scroll_down",
                -- ["<c-k>"] = "list_up",
                -- ["<c-j>"] = "list_down",
                -- ["<c-p>"] = "list_up",
                -- ["<c-n>"] = "list_down",
                ["gg"] = "list_top",
                ["G"] = "list_bottom",
                ["k"] = "list_up",
                ["j"] = "list_down",
                ["<c-q>"] = "qflist",
                ["<c-t>"] = "tab",
                -- ["<c-s>"] = "edit_split",
                -- ["<c-v>"] = "edit_vsplit",
                ["<c-w>H"] = "layout_left",
                ["<c-w>J"] = "layout_bottom",
                ["<c-w>K"] = "layout_top",
                ["<c-w>L"] = "layout_right",
                ["zb"] = "list_scroll_bottom",
                ["zt"] = "list_scroll_top",
                ["zz"] = "list_scroll_center",
                -- Additional
                ["<c-h>"] = "vsplit",
                ["<c-v>"] = "split",
                -- ["<CR>"] = "tabdrop",
                ["<c-CR>"] = "confirm",
                ["<C-c>"] = "close",
                ["<c-f>"] = "toggle_focus",
            },
            wo = {
                conceallevel = 2,
                concealcursor = "nvc",
            },
        },
        -- preview window
        preview = {
            keys = {
                ["<Esc>"] = "cancel",
                -- ["q"] = "close",
                ["i"] = "focus_input",
                ["<ScrollWheelDown>"] = "list_scroll_wheel_down",
                ["<ScrollWheelUp>"] = "list_scroll_wheel_up",
                ["<a-w>"] = "cycle_win",
                -- Additional
                ["<C-c>"] = { "close", mode = { "n", "i" } },
            },
        },
    },
}
