vim.cmd.colorscheme("kanagawa")
-- vim.cmd.colorscheme("vscode")

local border = "#777777"

vim.api.nvim_set_hl(0, "FloatBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspInfoBorder", { fg = border })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = border })
vim.api.nvim_set_hl(0, "DapUIFloatBorder", { fg = border })
vim.api.nvim_set_hl(0, "NullLsInfoBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspFloatWinBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspLinesDiagBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaHoverBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaRenameBorder", { fg = border })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaLspFinderBorder", { fg = border })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { fg = border })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaCodeActionBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaDefPreviewBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaDiagnosticBorder", { fg = border })
vim.api.nvim_set_hl(0, "ChatGPTTotalTokensBorder", { fg = border })
vim.api.nvim_set_hl(0, "CompeDocumentationBorder", { fg = border })
vim.api.nvim_set_hl(0, "LspSagaSignatureHelpBorder", { fg = border })

vim.api.nvim_set_hl(0, "LspInlayHint", { fg = "#757575" })

-- vim.cmd([[highlight FloatBorder guifg=#585858 guibg=None]])
-- vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
-- vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = "none" })
-- vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = "none" })
-- vim.api.nvim_set_hl(0, "VertSplit", { bg = "none" })
-- vim.api.nvim_set_hl(0, "VertSplit", { fg = "none" })
-- vim.api.nvim_set_hl(0, "FloatBorder", { fg = "white" })
-- vim.api.nvim_set_hl(0, "FloatBorder", { fg = "white", bg = "none" })
