local M = {
    -- #############################
    -- UI Plugins
    -- #############################

    -- nvim-ufo
    -- {
    --     "kevinhwang91/nvim-ufo",
    --     lazy = false,
    --     dependencies = { "kevinhwang91/promise-async" },
    --     config = function()
    --         require("plugin.config.ufo")
    --     end,
    -- },
    -- {
    --     "declancm/cinnamon.nvim",
    --     enabled = false,
    --     lazy = false,
    --     event = "VeryLazy",
    --     config = function()
    --         require("plugin.config.cinnamon")
    --     end,
    -- },
    -- Preview
    -- {
    --     "henriklovhaug/Preview.nvim",
    --     enabled = false,
    --     cmd = { "Preview" },
    --     event = "VeryLazy",
    --     config = function()
    --         require("plugin.config.Preview")
    --     end,
    -- },
    -- Outline
    -- {
    --     "hedyhli/outline.nvim",
    --     enabled = false,
    --     event = "VeryLazy",
    --     config = function()
    --         require("plugin.config.outline")
    --     end,
    -- },
    -- vim-illuminate
    -- {
    --     "RRethy/vim-illuminate",
    --     enabled = false,
    --     event = "VeryLazy",
    --     config = function()
    --         require("plugin.config.illuminate")
    --     end,
    -- },
    -- fidgit
    -- {
    --     "j-hui/fidget.nvim",
    --     enabled = false,
    --     opts = {
    --         -- options
    --     },
    --     config = function()
    --         require("fidget").setup()
    --     end,
    -- },
    -- {
    --     "rasulomaroff/reactive.nvim",
    --     enabled = false,
    --     event = "VeryLazy",
    --     lazy = false,
    --     config = function()
    --         require("plugin.config.reactive")
    --     end,
    -- },

    -- #############################
    -- Editting Plugins
    -- #############################

    -- conform
    -- {
    --     "stevearc/conform.nvim",
    --     enabled = false,
    --     opts = {},
    --     event = "VeryLazy",
    --     config = function()
    --         require("plugin.config.conform")
    --     end,
    -- },

    -- #############################
    -- LSP Plugins
    -- #############################

    -- guard
    -- {
    --     "nvimdev/guard.nvim",
    --     enabled = false,
    --     -- Builtin configuration, optional
    --     dependencies = {
    --         "nvimdev/guard-collection",
    --     },
    --     event = "VeryLazy",
    --     config = function()
    --         require("plugin.config.guard")
    --     end,
    -- },
    -- lsp_lines.nvim
    -- {
    --     "https://git.sr.ht/~whynothugo/lsp_lines.nvim",
    --     enabled = false,
    --     event = "LspAttach",
    --     lazy = false,
    --     config = function()
    --         require("plugin.config.lsp_lines")
    --     end,
    -- },
    -- Arduino.nvim
    -- {
    --   -- "edKotinsky/Arduino.nvim",
    --   "tom1484/Arduino.nvim",
    --   dependencies = {
    --     "neovim/nvim-lspconfig",
    --   },
    --   event = "VeryLazy",
    --   config = function()
    --     require("plugin.config.Arduino")
    --   end,
    -- },

    -- #############################
    -- Core Plugins
    -- #############################

    -- {
    --     "amitds1997/remote-nvim.nvim",
    --     enabled = false,
    --     event = "VeryLazy",
    --     version = "*", -- Pin to GitHub releases
    --     dependencies = {
    --         "nvim-lua/plenary.nvim", -- For standard functions
    --         "MunifTanjim/nui.nvim", -- To build the plugin UI
    --         "nvim-telescope/telescope.nvim", -- For picking b/w different remote methods
    --     },
    --     config = function()
    --         require("plugin.config.remote-nvim")
    --     end,
    -- },
}

return M
