return {
    options = {
        nu = true,
        relativenumber = true,
        smartindent = true,
        wrap = false,
        swapfile = false,
        backup = false,
        undofile = true,
        hlsearch = false,
        incsearch = true,
        scrolloff = 8,
        signcolumn = "yes",
        updatetime = 50,
        foldmethod = "indent",
        foldlevel = 99,
        showcmd = false,
        tagbsearch = false,
        showtabline = 0,
        list = true,
    },
    style = {
        border = "rounded",
    },
}
