-- vim.cmd("set termguicolors")
--
-- require("bufferline").setup({
-- 	options = {
-- 		mode = "tabs",
-- 		numbers = "ordinal",
-- 		diagnostics = "nvim_lsp",
-- 		offsets = {
-- 			{
-- 				filetype = "NvimTree",
-- 				text = "File Explorer",
-- 				text_align = "center",
-- 				separator = true,
-- 			},
-- 		},
-- 		separator_style = "thick",
-- 		always_show_bufferline = true,
-- 	},
-- })
