return {
    { mode = "n", lhs = "<leader>wt", rhs = ":tabe ", desc = "New tab" },
    { mode = "n", lhs = "<leader>wh", rhs = ":vsplit ", desc = "New vertical split" },
    { mode = "n", lhs = "<leader>wv", rhs = ":split ", desc = "New horizontal split" },
    { mode = "v", lhs = "J", rhs = ":m '>+1<CR>gv=gv", desc = "Move lines down", silent = true },
    { mode = "v", lhs = "K", rhs = ":m '<-2<CR>gv=gv", desc = "Move lines up", silent = true },
    { mode = "n", lhs = "<C-d>", rhs = "<C-d>zz", desc = "Scroll down", silent = true },
    { mode = "n", lhs = "<C-u>", rhs = "<C-u>zz", desc = "Scroll up", silent = true },
    { mode = { "n", "v" }, lhs = "<leader>y", rhs = [["+y]], desc = "Copy to system", silent = true },
    {
        mode = "n",
        lhs = "<leader>r",
        rhs = [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]],
        desc = "Replace word",
    },
    { mode = "n", lhs = "<leader>h", rhs = [[/\<<C-r><C-w>\>]], desc = "Search word" },
    { mode = "n", lhs = "<leader>1", rhs = "1gt", desc = "Tab 1", silent = true },
    { mode = "n", lhs = "<leader>2", rhs = "2gt", desc = "Tab 2", silent = true },
    { mode = "n", lhs = "<leader>3", rhs = "3gt", desc = "Tab 3", silent = true },
    { mode = "n", lhs = "<leader>4", rhs = "4gt", desc = "Tab 4", silent = true },
    { mode = "n", lhs = "<leader>5", rhs = "5gt", desc = "Tab 5", silent = true },
    { mode = "n", lhs = "<leader>6", rhs = "6gt", desc = "Tab 6", silent = true },
    { mode = "n", lhs = "<leader>7", rhs = "7gt", desc = "Tab 7", silent = true },
    { mode = "n", lhs = "<leader>8", rhs = "8gt", desc = "Tab 8", silent = true },
    { mode = "n", lhs = "<leader>9", rhs = "9gt", desc = "Tab 9", silent = true },
    { mode = "n", lhs = "<leader>0", rhs = "10gt", desc = "Tab 10", silent = true },
    {
        mode = "n",
        lhs = "B",
        rhs = require("utils.keymap").jump_to_last_buffer,
        desc = "Switch to previous buffer",
        silent = true,
    },
    {
        mode = "n",
        lhs = "W",
        rhs = ":w<CR>",
        desc = "Save",
        silent = true,
    },
    {
        mode = "n",
        lhs = "Q",
        rhs = ":q<CR>",
        desc = "Quit",
        silent = true,
    },
    { mode = { "i", "c" }, lhs = "<A-h>", rhs = "<S-LEFT>" },
    { mode = { "i", "c" }, lhs = "<A-j>", rhs = "<DOWN>" },
    { mode = { "i", "c" }, lhs = "<A-k>", rhs = "<UP>" },
    { mode = { "i", "c" }, lhs = "<A-l>", rhs = "<S-RIGHT>" },
    {
        mode = "n",
        lhs = "<C-Left>",
        rhs = "<cmd>vertical resize -2<cr>",
        desc = "Decrease width",
        silent = true,
    },
    {
        mode = "n",
        lhs = "<C-Right>",
        rhs = "<cmd>vertical resize +2<cr>",
        desc = "Increase width",
        silent = true,
    },
    {
        mode = "n",
        lhs = "<C-Down>",
        rhs = "<cmd>resize -2<cr>",
        desc = "Decrease height",
        silent = true,
    },
    {
        mode = "n",
        lhs = "<C-Up>",
        rhs = "<cmd>resize +2<cr>",
        desc = "Increase height",
        silent = true,
    },
    { mode = "t", lhs = "<Esc>", rhs = "<c-\\><c-n>" },
    {
        mode = "t",
        lhs = "<C-h>",
        rhs = "<cmd>TmuxNavigateLeft<cr>",
        desc = "Navigate left",
        silent = true,
    },
    {
        mode = "t",
        lhs = "<C-j>",
        rhs = "<cmd>TmuxNavigateDown<cr>",
        desc = "Navigate down",
        silent = true,
    },
    {
        mode = "t",
        lhs = "<C-k>",
        rhs = "<cmd>TmuxNavigateUp<cr>",
        desc = "Navigate up",
        silent = true,
    },
    {
        mode = "t",
        lhs = "<C-l>",
        rhs = "<cmd>TmuxNavigateRight<cr>",
        desc = "Navigate right",
        silent = true,
    },
}
